AdColony/MoPub-AdColony-PodSpecs/MoPub-AdColony-Adapters.podspec, AdMob/MoPub-AdMob-PodSpecs/MoPub-AdMob-Adapters.podspec, Chartboost/MoPub-Chartboost-PodSpecs/MoPub-Chartboost-Adapters.podspec, FacebookAudienceNetwork/MoPub-FacebookAudienceNetwork-Podspecs/MoPub-FacebookAudienceNetwork-Adapters.podspec, Flurry/MoPub-Flurry-PodSpecs/MoPub-Flurry-Adapters.podspec, IronSource/MoPub-IronSource-PodSpecs/MoPub-IronSource-Adapters.podspec, OnebyAOL/MoPub-OnebyAOL-Podspecs/MoPub-OnebyAOL-Adapters.podspec, Tapjoy/MoPub-Tapjoy-PodSpecs/MoPub-TapJoy-Adapters.podspec, UnityAds/MoPub-UnityAds-PodSpecs/MoPub-UnityAds-Adapters.podspec, Vungle/MoPub-Vungle-PodSpecs/MoPub-Vungle-Adapters.podspec
added checks for static libraries in podspecs to remove transitive dependency issues with the pods.
=> Pod spec changes to fix transitive dependencies

OnebyAOL/MoPub-OnebyAOL-Podspecs/LICENSE, OnebyAOL/MoPub-OnebyAOL-Podspecs/README
removing license and podspecs for AOL as its no longer applicable.
=> Update and rename LICENSE to README

FacebookAudienceNetwork/Changelog.md, FacebookAudienceNetwork/FacebookAdvancedBidder.h, FacebookAudienceNetwork/FacebookAdvancedBidder.m, FacebookAudienceNetwork/FacebookBannerCustomEvent.m, FacebookAudienceNetwork/FacebookInterstitialCustomEvent.m, FacebookAudienceNetwork/FacebookNativeCustomEvent.m, FacebookAudienceNetwork/FacebookRewardedVideoCustomEvent.m, FacebookAudienceNetwork/MoPub-FacebookAudienceNetwork-Podspecs/MoPub-FacebookAudienceNetwork-Adapters.podspec
=> ADF-3067: Retrofit Facebook Audience Network for Advanced Bidding

Chartboost/CHANGELOG.md, Chartboost/ChartboostRewardedVideoCustomEvent.m, Chartboost/MPChartboostRouter.m, Chartboost/MoPub-Chartboost-PodSpecs/MoPub-Chartboost-Adapters.podspec
=> Override Chartboost's didDismissRewardedVideo

FacebookAudienceNetwork/CHANGELOG.md, FacebookAudienceNetwork/FacebookNativeAdAdapter.m, FacebookAudienceNetwork/FacebookNativeCustomEvent.m, FacebookAudienceNetwork/MoPub-FacebookAudienceNetwork-Podspecs/MoPub-FacebookAudienceNetwork-Adapters.podspec
=> Fix Facebook Audience Network native adapter to work with FAN SDK 4.99

AdMob/CHANGELOG.md, AdMob/MPGoogleAdMobBannerCustomEvent.h, AdMob/MPGoogleAdMobBannerCustomEvent.m, AdMob/MPGoogleAdMobInterstitialCustomEvent.h, AdMob/MPGoogleAdMobInterstitialCustomEvent.m, AdMob/MPGoogleAdMobNativeAdAdapter.h, AdMob/MPGoogleAdMobNativeAdAdapter.m, AdMob/MPGoogleAdMobNativeCustomEvent.h, AdMob/MPGoogleAdMobNativeCustomEvent.m, AdMob/MPGoogleAdMobNativeRenderer.h, AdMob/MPGoogleAdMobNativeRenderer.m, AdMob/MPGoogleAdMobRewardedVideoCustomEvent.h, AdMob/MPGoogleAdMobRewardedVideoCustomEvent.m, AdMob/MPGoogleGlobalMediationSettings.h, AdMob/MoPub-AdMob-PodSpecs/MoPub-AdMob-Adapters.podspec
* Added Unified Native Ad and removed deprecated native ad types.
* Added MediaView instance.
=> Updating AdMob Adapter to use Unified native Ad and MediaView.

OnebyAOL/CHANGELOG.md, OnebyAOL/MillennialNativeAdAdapter.m, OnebyAOL/MoPub-OnebyAOL-Podspecs/MoPub-OnebyAOL-Adapters.podspec
* Certify with AOL 6.8.1.0
* Fix native ad images not shown
* Fix impression and click tracking action
=> Prepare AOL adapters for release - 6.8.1.0

AppLovin/README.md
The current tutorial link is broken.
=> Update AppLovin README.md

.github/ISSUE_TEMPLATE/ios-mediation-issue-template.md
=> Update issue templates

FacebookAudienceNetwork/CHANGELOG.md, FacebookAudienceNetwork/FacebookAdapterConfiguration.m, FacebookAudienceNetwork/MoPub-FacebookAudienceNetwork-Podspecs/MoPub-FacebookAudienceNetwork-Adapters.podspec
Prepare Facebook Audience Network release 5.4.0
=> Facebook adapters release - 5.4.0.0

AppLovin/AppLovinAdapterConfiguration.m, AppLovin/AppLovinBannerCustomEvent.m, AppLovin/CHANGELOG.md, AppLovin/MoPub-Applovin-PodSpecs/MoPub-Applovin-Adapters.podspec
The changes in this PR are related to the email we sent earlier related to the subject line `[AppLovin] Upcoming MoPub Banner and Medium Rectangle Banner changes`.
Please let us know if these changes look good to you. Thanks!
=> AppLovin adapter updates for banner - 6.7.1.1

FacebookAudienceNetwork/CHANGELOG.md, FacebookAudienceNetwork/FacebookAdapterConfiguration.m
Updated for the FB AN SDK 5.5.1
=> Updated for 5.5.1

FacebookAudienceNetwork/CHANGELOG.md, FacebookAudienceNetwork/FacebookAdapterConfiguration.h, FacebookAudienceNetwork/FacebookAdapterConfiguration.m, FacebookAudienceNetwork/FacebookNativeAdAdapter.h, FacebookAudienceNetwork/FacebookNativeAdAdapter.m, FacebookAudienceNetwork/FacebookNativeAdRenderer.m, FacebookAudienceNetwork/FacebookNativeCustomEvent.m
Update for FAN 5.6 plus support for native banner.
=> Adapters for FAN 5.6 plus native banner support

AppLovin/AppLovinAdapterConfiguration.h, AppLovin/AppLovinAdapterConfiguration.m, AppLovin/CHANGELOG.md
Remove isTestMode from adapter
=> support AppLovinSDK 6.10.0 version 

Vungle/CHANGELOG.md, Vungle/VungleAdapterConfiguration.m, Vungle/VungleBannerCustomEvent.m, Vungle/VungleInterstitialCustomEvent.m, Vungle/VungleRouter.h, Vungle/VungleRouter.m
Vungle iOS MoPub Adapter 6.5.2.0 Release
* This version of the adapter is compatible with Vungle 6.5.2.
* Add support for Flexible Banner.
=> Release Vungle adapter 6.5.2.0

Vungle/CHANGELOG.md, Vungle/VungleAdapterConfiguration.m, Vungle/VungleBannerCustomEvent.m
To fix issue reported here - https://github.com/mopub/mopub-ios-mediation/issues/279
@ashinagawa, feel free to take a look and let us know if you have any questions.
=> Release Vungle adapters - 6.5.3.1

Vungle/CHANGELOG.md, Vungle/VungleAdapterConfiguration.h, Vungle/VungleAdapterConfiguration.m, Vungle/VungleBannerCustomEvent.m, Vungle/VungleInstanceMediationSettings.h, Vungle/VungleInterstitialCustomEvent.m, Vungle/VungleRewardedVideoCustomEvent.m, Vungle/VungleRouter.h, Vungle/VungleRouter.m
This version of the adapters follows MoPub code style guidelines and has been certified with Vungle 6.7.0.
=> Release Vungle adapter- 6.7.0.0

Vungle/CHANGELOG.md, Vungle/VungleAdapterConfiguration.m, Vungle/VungleBannerCustomEvent.m, Vungle/VungleInterstitialCustomEvent.m, Vungle/VungleRewardedVideoCustomEvent.m, Vungle/VungleRouter.m
Vungle MoPub Adapter 6.7.1.0 is compatible with Vungle SDK 6.7.1.
=> Release Vungle - 6.7.1.0

Vungle/CHANGELOG.md, Vungle/VungleAdapterConfiguration.m, Vungle/VungleBannerCustomEvent.m, Vungle/VungleInstanceMediationSettings.h, Vungle/VungleInterstitialCustomEvent.m, Vungle/VungleRewardedVideoCustomEvent.m, Vungle/VungleRouter.h, Vungle/VungleRouter.m
This version of the adapters has been certified with Vungle 6.9.1 and MoPub SDK 5.15.0.
=> Release Vungle - 6.9.1.0

AdMob/CHANGELOG.md, AdMob/GoogleAdMobAdapterConfiguration.m, AdMob/MPGoogleAdMobBannerCustomEvent.m, AdMob/MPGoogleAdMobInterstitialCustomEvent.m, AdMob/MPGoogleAdMobNativeAdAdapter.h, AdMob/MPGoogleAdMobNativeAdAdapter.m, AdMob/MPGoogleAdMobNativeCustomEvent.m, AdMob/MPGoogleAdMobNativeRenderer.m, AdMob/MPGoogleAdMobRewardedVideoCustomEvent.m
Pushing a draft for code review purposes
=> Google - 8.3.0.0
