mopub/mopub-ios-mediation

FacebookAudienceNetwork/Changelog.md
FacebookAudienceNetwork/FacebookNativeAdAdapter.m

Removed star rating from the native ad adapter since it has been deprecated by Facebook.

Removed star rating from FB's native ad adapter

---

Flurry/FlurryNativeVideoAdRenderer.h

Swift sample app wouldn't build because of this.

Fixes header import in Flurry Native Video Ad Renderer for manual integrations

---

AdMob/MPGoogleAdMobInterstitialCustomEvent.m
AdMob/MPGoogleAdMobNativeAdAdapter.m
AdMob/MPGoogleAdMobNativeRenderer.m
OnebyAOL/MPMillennialBannerCustomEvent.m

The `#imports` deleted here reference headers that are not exposed in the MoPub SDK framework target, and best I can tell, are not actually used in the adapters that reference them.
I've tested that these changes build in Canary with the exception of the Millennial change. I'm 95% sure the Millennial change will work too, just don't have the testing environment for it.

ADF-3563: Removes references to unused headers

---

OnebyAOL/CHANGELOG.md
OnebyAOL/MPMillennialBannerCustomEvent.m
OnebyAOL/MPMillennialInterstitialCustomEvent.m
OnebyAOL/MPMillennialRewardedVideoCustomEvent.m
OnebyAOL/MillennialNativeAdAdapter.h
OnebyAOL/MillennialNativeAdAdapter.m
OnebyAOL/MillennialNativeCustomEvent.m
OnebyAOL/MoPub-OnebyAOL-Podspecs/MoPub-OnebyAOL-Adapters.podspec

* Roll back consent passing per AOL's request.
* Fix a duplicate symbol issue in the native ad adapter.

Roll back GDPR/consent passing for One by AOL

---

AdMob/CHANGELOG.md
AdMob/MPGoogleAdMobInterstitialCustomEvent.m
AdMob/MoPub-AdMob-PodSpecs/MoPub-AdMob-Adapters.podspec

**Banner**: Not added because AdMob does not have an equivalent callback (https://developers.google.com/mobile-ads-sdk/docs/dfp/ios/banner#implementing_banner_events).
**Interstitial**: Added to when AdMob fires its `interstitialWillPresentScreen` delegate (https://developers.google.com/mobile-ads-sdk/docs/dfp/ios/interstitial#implementing_interstitial_events). This is a little early - right before the interstitial appears, but AdMob does not have a "didPresentScreen" delegate.

AdMob - Add interstitial manual impression tracking

---

AdMob/CHANGELOG.md
AdMob/MPGoogleAdMobInterstitialCustomEvent.m
AdMob/MoPub-AdMob-PodSpecs/MoPub-AdMob-Adapters.podspec

Does the same as https://github.com/mopub/mopub-ios-mediation/pull/87.

AdMob interstitial to use initWithAdUnitID - 7.32.0.1

---

FacebookAudienceNetwork/CHANGELOG.md
FacebookAudienceNetwork/FacebookBannerCustomEvent.m
FacebookAudienceNetwork/FacebookNativeAdAdapter.m
FacebookAudienceNetwork/FacebookNativeCustomEvent.m
FacebookAudienceNetwork/MoPub-FacebookAudienceNetwork-Podspecs/MoPub-FacebookAudienceNetwork-Adapters.podspec

* Certify with FB Audience Network 5.0.0.
* Remove calls to disableAutoRefresh for banner (deprecated by Facebook).
* Expose the advertiser name asset.

Certify FB adapters - 5.0.0.0

---

Vungle/CHANGELOG.md
Vungle/MPVungleRouter.m
Vungle/MoPub-Vungle-PodSpecs/MoPub-Vungle-Adapters.podspec

Remove remaining code pertaining to Vungle's placement IDs (`pids`) since it's no longer needed to initialize Vungle.

Prepare Vungle adapters for release - 6.2.0.2

---

Flurry/CHANGELOG.md
Flurry/FlurryMPConfig.m
Flurry/MoPub-Flurry-PodSpecs/MoPub-Flurry-Adapters.podspec

* Certify with Flurry 9.2.0
* Replace `setDebugLogEnabled`, which was deprecated, with `setLogLevel:FlurryLogLevelDebug`

Prepare Flurry adapters for release - 9.2.0.0

---

UnityAds/CHANGELOG.md
UnityAds/MPUnityRouter.m
UnityAds/MoPub-UnityAds-PodSpecs/MoPub-UnityAds-Adapters.podspec

Make the Unity Ads router throw an error to the delegate when no_fill is detected.
This should properly notify the Mopub SDK in a no_fill scenario, and improve the 30 second timeout behavior

Add no_fill detection to Unity Ads adaptor

---

UnityAds/CHANGELOG.md
UnityAds/MPUnityRouter.h
UnityAds/MPUnityRouter.m
UnityAds/MoPub-UnityAds-PodSpecs/MoPub-UnityAds-Adapters.podspec
UnityAds/UnityAdsBannerCustomEvent.h
UnityAds/UnityAdsBannerCustomEvent.m
UnityAds/UnityAdsInterstitialCustomEvent.m
UnityAds/UnityAdsRewardedVideoCustomEvent.m

This PR will add UnityAds Banner support and does some small cleanup to the codebase. Note that UnityAds Banner currently only supports a single banner instance.
- iPhone XS 12.0
- iPhone 8+ 11.0

Adds Banner support for UnityAds

---

AdMob/CHANGELOG.md
AdMob/MoPub-AdMob-PodSpecs/MoPub-AdMob-Adapters.podspec

This fixes a flood of linker warnings during archiving https://github.com/firebase/firebase-ios-sdk/issues/196#issuecomment-437198306

[Pods] Update Google-Mobile-Ads-SDK to 7.35.2

---

Flurry/CHANGELOG.md
Flurry/FlurryNativeVideoAdRenderer.m
Flurry/MoPub-Flurry-PodSpecs/MoPub-Flurry-Adapters.podspec

protect against another adapter being used in FlurryRenderer, which results in crash. This behavior matches the MPGoogleAdMobNativeRenderer
Example stack trace:
`
6 | app | -[FlurryNativeVideoAdRenderer setupVideoView] (FlurryNativeVideoAdRenderer.m:166)
-- | -- | --
7 | app | -[FlurryNativeVideoAdRenderer retrieveViewWithAdapter:error:] (FlurryNativeVideoAdRenderer.m:77)
8 | MoPub | -[MPNativeAd retrieveAdViewWithError:] (MPNativeAd.m:96)
9 | app | __34-[MoPubAdUnit makeNativeAdRequest]_block_invoke (MoPubAdUnit.m:467)
10 | MoPub | __45-[MPNativeAdRequest assignCompletionHandler:]_block_invoke (MPNativeAdRequest.m:131)
11 | MoPub | -[MPNativeAdRequest completeAdRequestWithAdObject:error:] (MPNativeAdRequest.m:249)
12 | MoPub | -[MPNativeAdRequest nativeCustomEvent:didLoadAd:] …

FlurryRenderer fix

---

Chartboost/CHANGELOG.md
Chartboost/MPChartboostRouter.m
Chartboost/MoPub-Chartboost-PodSpecs/MoPub-Chartboost-Adapters.podspec

Chartboost GDPR control method changed from
> + (void)restrictDataCollection:(BOOL)shouldRestrict
to 
> + (void)setPIDataUseConsent:(CBPIDataUseConsent)consent;

Add new Chartboost GDPR method, remove deprecated one

---

AppLovin/AppLovinInterstitialCustomEvent.m
AppLovin/CHANGELOG.md
AppLovin/MoPub-Applovin-PodSpecs/MoPub-Applovin-Adapters.podspec

In AppLovin's latest iOS SDK v. 6.1.0, we have removed conditional nullability annotations such as `alnonnull` and `alnullability` which provided backwards compatibility for publishers on < Xcode 6. Thus, this adapter must be updated as well to provide compatibility.

Prepare adapters for release - AppLovin 6.1.4.0

---

FacebookAudienceNetwork/CHANGELOG.md
FacebookAudienceNetwork/FacebookAdapterConfiguration.m
FacebookAudienceNetwork/FacebookNativeAdRenderer.m
FacebookAudienceNetwork/MoPub-FacebookAudienceNetwork-Podspecs/MoPub-FacebookAudienceNetwork-Adapters.podspec

Fixed bug in Native ads with causes crashes in some scenarios.
Replace hardcoded FBSDK version with the value in the header.
Replace adapter initialization logic with FAN SDK initialization callback

Facebook adapters release - 5.3.2.1

---

Tapjoy/CHANGELOG.md
Tapjoy/MoPub-Tapjoy-PodSpecs/MoPub-TapJoy-Adapters.podspec
Tapjoy/TapjoyAdapterConfiguration.m
Tapjoy/TapjoyInterstitialCustomEvent.m
Tapjoy/TapjoyRewardedVideoCustomEvent.m

This PR is regarding` didClick` callback support for Tapjoy adapter for Mopub iOS SDK.  `didClick ` callback will fire when a click event has occurred on Tapjoy placement. 
What's new:
- (void)didClick:(TJPlacement*)placement is added to TapjoyInterstitialCustomEvent.m and TapjoyRewardedVideoCustomEvent.m classes of Tapjoy iOS adapter.
*Notes: `didClick ` callback  won't get fired or be fully functioning currently until Tapjoy server change is completed near future.
How to test:
- Run MoPub sample app with latest Mopub SDK, Tapjoy SDK and Tapjoy Adapter from this branch.
- Request Tapjoy video placement. 
- Show and play the video ads.
- Perform a click on video ads and observe in Logcat if `didClick` callback gets fired on this placement from Tapjoy Network.

Feature/didClick Tapjoy_Mopub iOS adapter support

---

FacebookAudienceNetwork/CHANGELOG.md
FacebookAudienceNetwork/FacebookAdapterConfiguration.m
FacebookAudienceNetwork/FacebookBannerCustomEvent.m
FacebookAudienceNetwork/MoPub-FacebookAudienceNetwork-Podspecs/MoPub-FacebookAudienceNetwork-Adapters.podspec

The changes in this PR are related to the email we sent earlier related to the subject line `[Facebook] Upcoming MoPub Banner and Medium Rectangle Banner changes.`
Please let us know if these changes look good to you. Thanks!

Facebook Audience Network Adapter updates for banner - 5.4.0.1

---

AppLovin/AppLovinBannerCustomEvent.m
AppLovin/CHANGELOG.md

@thomasmso, does it sound good to remove this `else` block that handles failures? Right now there are 2 `else`s.

AppLovin - Remove extraneous `else` block in the banner adapter

---

Tapjoy/CHANGELOG.md
Tapjoy/MoPub-Tapjoy-PodSpecs/MoPub-TapJoy-Adapters.podspec
Tapjoy/TapjoyAdapterConfiguration.m
Tapjoy/TapjoyRewardedVideoCustomEvent.m

This PR is to implement TJPlacementVideoDelegate properly so that`TJPlacementVideoDelegate` callbacks get called correctly and some logging correction in `TapjoyRewardedVideoCustomEvent.m`. 
How to test:
- Run MoPub sample app with latest Mopub SDK, Tapjoy SDK and Tapjoy Adapter from this branch.
- Request Tapjoy video placement.
- Put break points on `videoDidStart`, `videoDidComplete`callbacks.
- Show and play the video ads.
- Observe if `videoDidStart`, `videoDidComplete`callbacks get fired.

Release Tapjoy adapters 12.3.1.3

---

AppLovin/AppLovinAdapterConfiguration.m
AppLovin/AppLovinBannerCustomEvent.m
AppLovin/AppLovinInterstitialCustomEvent.m
AppLovin/AppLovinRewardedVideoCustomEvent.m
AppLovin/CHANGELOG.md

Hey @thomasmso, could you help take a look at the proposed change here? We would like to fail fast and bail out if the SDK Key is not available (either from the Info.plist or programmatically passed in through MoPub's initialization). Otherwise, execution will get stuck as we don't get any callback or signal from AppLovin for the absence of the SDK Key. Thanks!

AppLovin - Fail fast if SDK Key is not available - 6.9.4.1

---

Chartboost/CHANGELOG.md
Chartboost/ChartboostAdapterConfiguration.m

Produces loss of precision warning on 64 bit builds.

No need to downcast to int to switch on this enum.

---

UnityAds/CHANGELOG.md
UnityAds/UnityAdsAdapterConfiguration.m
UnityAds/UnityRouter.m

Currently, Unity SDK has two different behaviors for loading ads: 
1. request and caching full screen ads for all placements right after SDK initialized.
2. request ads for one placement by the time call load.
This PR is to change Unity Adapter to handle this better.
Unity SDK will trigger UnityRouterDelegate every time ` [UnityAds load:placementId];` is called for both behaviors and adapter will handle both  seamless. 
NOTE:
This feature will be only apply for adapters with specific versions, e.g. 3.3.0.1.

Release Unity Ads adapter 3.3.0.1

---

AppLovin/AppLovinAdapterConfiguration.m
AppLovin/AppLovinBannerCustomEvent.m
AppLovin/CHANGELOG.md

There were several compiler warnings due to recently deprecated properties and functions in ALAdSize.

AppLovin - Fix compiler warnings - 6.10.2.0

---

Vungle/CHANGELOG.md
Vungle/VungleAdapterConfiguration.m

Vungle iOS MoPub Adapter 6.5.3.0 Release
- This version of adapter is compatible with Vungle 6.5.3 SDK.

Release Vungle adapter 6.5.3.0

---

Vungle/CHANGELOG.md
Vungle/VungleAdapterConfiguration.m

This version of the adapters has been certified with Vungle 6.8.0 and MoPub SDK 5.13.1.

Release 6.8.0.0 Vungle MoPub Adapter

---

AdMob/CHANGELOG.md
AdMob/GoogleAdMobAdapterConfiguration.m
AdMob/MPGoogleAdMobBannerCustomEvent.m

Requesting a rect then immediately a banner can result in ignoring the mrect response as the banner size was kept in two static variables

Fix race condition between rect and banner request
